export const FIELDS = [
  { index: 0, goesTo: 0, sleep: 0, },
  { index: 1, goesTo: 0, sleep: 0, },
  { index: 2, goesTo: 0, sleep: 0, },
  { index: 3, goesTo: 0, sleep: 0, },
  { index: 4, goesTo: 0, sleep: 0, },
  { index: 5, goesTo: 7, sleep: 0, },
  { index: 6, goesTo: 13, sleep: 0, },
  { index: 7, goesTo: 0, sleep: 0, },
  { index: 8, goesTo: 10, sleep: 0, },
  { index: 9, goesTo: 0, sleep: 0, },
  { index: 10, goesTo: 0, sleep: 0, },
  { index: 11, goesTo: 9, sleep: 0, },
  { index: 12, goesTo: 0, sleep: 0, },
  { index: 13, goesTo: 0, sleep: 0, },
  { index: 14, goesTo: 7, sleep: 0, },
  { index: 15, goesTo: 0, sleep: 0, },
  { index: 16, goesTo: 23, sleep: 0, },
  { index: 17, goesTo: 0, sleep: 0, },
  { index: 18, goesTo: 0, sleep: 0, },
  { index: 19, goesTo: 0, sleep: 0, },
  { index: 20, goesTo: 0, sleep: 0, },
  { index: 21, goesTo: 0, sleep: 0, },
  { index: 22, goesTo: 18, sleep: 0, },
  { index: 23, goesTo: 0, sleep: 0, },
  { index: 24, goesTo: 0, sleep: 2, },
  { index: 25, goesTo: 23, sleep: 0, },
  { index: 26, goesTo: 27, sleep: 0, },
  { index: 27, goesTo: 0, sleep: 0, },
  { index: 28, goesTo: 0, sleep: 0, },
  { index: 29, goesTo: 34, sleep: 0, },
  { index: 30, goesTo: 0, sleep: 0, },
  { index: 31, goesTo: 0, sleep: 0, },
  { index: 32, goesTo: 0, sleep: 0, },
  { index: 33, goesTo: 0, sleep: 0, },
  { index: 34, goesTo: 29, sleep: 0, },
  { index: 35, goesTo: 37, sleep: 0, },
  { index: 36, goesTo: 0, sleep: 0, },
  { index: 37, goesTo: 0, sleep: 0, },
  { index: 38, goesTo: 0, sleep: 0, },
  { index: 39, goesTo: 36, sleep: 0, },
  { index: 40, goesTo: 0, sleep: 0, },
  { index: 41, goesTo: 0, sleep: 0, },
  { index: 42, goesTo: 0, sleep: 1, },
  { index: 43, goesTo: 0, sleep: 0, },
  { index: 44, goesTo: 41, sleep: 0, },
  { index: 45, goesTo: 0, sleep: 0, },
  { index: 46, goesTo: 33, sleep: 0, },
  { index: 47, goesTo: 0, sleep: 0, },
  { index: 48, goesTo: 45, sleep: 0, },
  { index: 49, goesTo: 47, sleep: 0, },
  { index: 50, goesTo: 0, sleep: 0, },
];

export const FIELDS_CHUNKED = [];
let i, chunk = 9;
for (i = 0; i < FIELDS.length; i += chunk) {
  let tmp = FIELDS.slice(i, i + chunk);
  if (i / chunk % 2) tmp = tmp.reverse();
  FIELDS_CHUNKED.push(...tmp);
}
